### ISSUE TITLE
Install this plugin with release install

### ISSUE THREAD

**Issue by JohnKirk1337** [Crivella/ocr_translate-paddle#1]
There's no accessible settings.py. How can I use this plugin with the release version?

**Comment by Crivella** [comment]
This is related to https://github.com/Crivella/ocr_translate/issues/23.
Unfortunately it is not trivial to allow managing plugins in a frozen bundle (the way I am producing the release files). For now the only way would be to install following one of the other procedures like https://crivella.github.io/ocr_translate/install/index.html#from-github

I am planning to incorporate Paddle in the next release of the main tool, but I haven't had the time to work on a few features i would like to add before that.
